In [ ]:
EDA => Exploratory Data Analysis => Problem Solving

- Penguasaan Domain / Business Knowledge ==> Riset

- Context dari Data/Project
- Define Problem & Audience
- Finding data ==> Data Collection 
- Pahamin setiap Kolom dan isinya

++++++++++++++++++++++++++++++++++++++++++ Teknikal +++++++++++++++++++++++++++++++++++++
## Data Wrangling - Data Preparation
- Pengecekan Tipe data
- Pengecekan Duplikat
- Pengecekan Missing Values - dan bagaimana cara handlingnya
- Describe data - Statistik deskriptif
- Pengecekan Outliers
- Optional : Pengecekan Data Formatting
- Optional : Pengecekan Kolom bertipe tanggal/Date time ==> Ekstraksi

## Data Analysis
- Analisa data dg Tabular ==> Crosstab. Pivot table, Group by
    - Univariate : Analisa per 1 kolom
    - BiVariate / Multivariate : Analisa 2 atau lebih kolom
    - Temukan Insight dari Hasil Analisa
- Analisa data dg Grafik.Plot ==> data visualization
    - Univariate : Analisa per 1 kolom
    - BiVariate / Multivariate : Analisa 2 atau lebih kolom
    - Temukan Insight dari Hasil Analisa
### Kesimpulan & Actionable Recommendation - Rekomendasi
- Summary dari Insight data
- Rekomendasi untuk Audience/stakeholder
- Impactful untuk Bisnis ==> Solve the problem

Data Analyst != Data Reporter
Problem solving using Data

# Data Cleaning

In [ ]:
## Missing Value Handling

In [ ]:
Teknikal Handling : Drop - Fill

Drop :
    - Drop Kolom
    - Drop Baris
    
----> Tanya ke Sumber pemilik data ==> Paling utama & Prioritas
----> Tanya Atasan

++++++++++++++++++++++++++++++++++++++Analisis Teknikal+++++++++++++++++++++++++++++++++++++++++++
Drop Kolom df.drop(AXIS=1):
    - Terdapat kolom pengganti/kolom lain yg lebih lengkap tetapi memiliki Tujuan/fungsi yg sama
    Jarak (meter) ==> Ada Missing Value ==> Bisa langsung drop kolom
    Jarak (Km) v==> Tidak ada Missing Value
    
    Price (USD) ==> Ada Missing value ==> langsung drop Kolom
    Price (IDR) ==> Tidak ada Missing value
    
    - Kolom tsb Tidak akan digunakan untuk Analisa maupun Building Machine Learning
    Kolom Nama ==> ada Missing Value ==> Drop Kolom
    - Jumlah Missing Value diatas 70% ==> atau diatas 50% dan data sudah dianalisa terlebih dahulu (Quick Analysis)
Drop Baris df.drop(Axis=0):
    - Jumlah data sangat banyak, misal jumlah baris 10 juta, baris NaN ada 5 baris
    - Lihat berapa Kolom yg kosong : Misal kita punya 10 kolom, ada beberapa data yg kolomnya missing sampai 8 kolom
    - Target Analisa yg Missing : Misal kita ingin analisa Jumlah Sales, ketika ada baris yg Missing di Kolom Sales, langsung Drop baris tsb
Fillna df.fillna(): Mengisi dg Data Sintetis / Data Buatan
    - Mengisi dg Algoritma
    - Mengisi dg memperhatikan kolom lain/Features lain
    Opsi Fillna :
        - Mean : Data numerik/continous       ==> Data terdistribusi Normal / Tidak ada Outliers
        - Median : Data numerik/continous     ==> Gunakan jika ada Outliers
        - Modus : Most Frequent ==> Data Kategorikal

In [ ]:
Nama - Jabatan - Kota - Usia - Pendidikan - Gaji - Performance - Promosi - sales
1
2
3
4
7
8
9

Missing ==> Gaji
Lihat kolom lain : Jabatan & Kota

In [ ]:
## Duplicate / Redundant Data Handling

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
'Brand' :['Sedaap','Sedaap', 'Indomie','Indomie','Indomie'],
'Package':['Cup', 'Cup', 'Cup', 'Pack', 'Pack'],
'Rating' :[4, 4, 2.5, 4.5, 5]})
df

     Brand Package  Rating
0   Sedaap     Cup     4.0
1   Sedaap     Cup     4.0
2  Indomie     Cup     2.5
3  Indomie    Pack     4.5
4  Indomie    Pack     5.0

In [3]:
df.drop_duplicates() ## Akan menghapus baris yg memiliki duplikat, Isi dari semua kolom Sama
## Umumnya pake ini tetapi bisa d sesuaikan dg kebutuhan

     Brand Package  Rating
0   Sedaap     Cup     4.0
2  Indomie     Cup     2.5
3  Indomie    Pack     4.5
4  Indomie    Pack     5.0

In [4]:
df

     Brand Package  Rating
0   Sedaap     Cup     4.0
1   Sedaap     Cup     4.0
2  Indomie     Cup     2.5
3  Indomie    Pack     4.5
4  Indomie    Pack     5.0

In [6]:
df.drop_duplicates(subset=['Brand']) ## Hapus baris duplikat berdasarkan kolom tertentu (Brand)

     Brand Package  Rating
0   Sedaap     Cup     4.0
2  Indomie     Cup     2.5

In [7]:
df.drop_duplicates(subset=['Brand','Package'])
## Menggunakan nilai Keep default ==> keep ==> First

     Brand Package  Rating
0   Sedaap     Cup     4.0
2  Indomie     Cup     2.5
3  Indomie    Pack     4.5

In [8]:
df.drop_duplicates(subset=['Brand','Package'], keep = 'last')

     Brand Package  Rating
1   Sedaap     Cup     4.0
2  Indomie     Cup     2.5
4  Indomie    Pack     5.0

In [ ]:
## Outliers Handling