In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Telco.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
A

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
pd.to_numeric(df['TotalCharges'])

ValueError: Unable to parse string " " at position 488

In [7]:
df.iloc[[488]]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No

In [9]:
df.drop(488, inplace=True)

In [16]:
len(df)

7032

In [11]:
df[df['TotalCharges'] == ' ']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [13]:
df = df[df['TotalCharges'] != ' ']
## Handle Data Formatting

In [14]:
pd.to_numeric(df['TotalCharges'])

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7032, dtype: float64

In [15]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])
## Mengubah Tipe data menjadi Numerik

In [18]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   7032.000000
mean        0.162400    32.421786       64.798208   2283.300441
std         0.368844    24.545260       30.085974   2266.771362
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.587500    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.862500   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [20]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [22]:
df.groupby('gender') ## Kolom yg digunakan dalam Group By harus Kategorikal (Diskrit)

In [23]:
df.groupby('gender').mean()
## Gunakan fungsi Agregasi data sesuai dg kebutuhan
## Ketika menggunakan Fungsi agregat, Seluruh kolom selain Kolom group by akan di kalkulasi

TypeError: Could not convert 7590-VHVEG9237-HQITU9305-CDSKC6713-OKOMC7892-POOKP3655-SNQYZ8191-XWSZG4190-MFLUW4183-MYFRB3638-WEABW6865-JZNKO8773-HHUOZ3841-NFECX6827-IEAUQ6234-RAAPL6572-ADKRS8168-UQWWF9489-DEDVP9867-JCZSP4671-VJLCL4080-IIARD3714-NTNFO7760-OYPDY2954-PIBKO8012-SOUDQ9420-LOJKX6575-SUVOI7495-OOKFY4667-QONEA8769-KKTPH3957-SQXML5954-BDFSG0434-CSFON0557-ASKVU5698-BQJOH5122-CYFXA3410-YOQBQ3170-NMYVV0731-EBJQB5630-AHZIL2673-CXQEU6416-JNVRK5590-ZSKRV3887-PBQAO5919-TMRGD8108-UXRQN9191-MYQKX9919-YLNNG0318-ZOPWS4808-YNLEU1862-QRWPE2796-NNUFI6067-NGCEU8637-XJIVR4598-XLKNJ3679-XASPY5386-THSLQ6728-DKUCO9750-BOOHV4549-ZDQYY5712-AHQNN4846-WHAFZ5256-SKJGO9560-BBZXK5299-RULOA8402-OOOHJ1091-SOZGA2928-HLDBA6497-TILVL7219-TLZHO4412-YLTKF2876-GZYZC6207-WIOLX7799-LGRDP7850-VWJUU3774-VBNXY0390-DCFDQ3146-MSEGF4080-OGPJL1095-WGNGG5716-EZXZN3780-YVMFA1679-JRFBR3077-RSNTJ6551-GNYDG9167-APMXZ8992-VONJD0867-MKZVY4482-EWFMI2907-ILJBN3376-BMGFE1159-WFSGR1875-QIVME0691-JVSYA5918-VUKWP1744-JHKYS2656-FMOKZ2070-FNEXE5947-SGKCL6317-YPKDH6582-OIVSP1918-ZBFQJ1024-GUALD0956-SYCWG8017-UVSZU2984-RGEYA9680-NIAUV2604-IJPDU9323-HGFWY8544-GOQSH7674-YTAFD7825-ECJRF4195-NZGTA4709-LKHYG0699-NDKJM6496-JDSSB9408-SSNVZ4443-EMBNA5961-VUSRV6341-JVQGF2232-DMLXU0945-TSONX7083-MIOPC1984-GPTEH0621-JFHOL0094-OIFMO7301-ABVAD7576-ASEJU9058-HRZSV4522-AKYLR4075-JFPGR4629-NRXKX4111-BNXIF7017-VFHAY4959-JOSRX5046-NUHWD7605-BDWDC1950-KSVVJ0123-CRBRT3197-ARFOY7014-ZZXAW4385-GZQXV4484-GLZOU4130-MZLCC0314-TKOSI8229-MYEJZ2080-SRCDE9577-WJVCQ6202-DYYFX3808-HFKDE4847-TAJYI1563-IWQEX6556-DBKZF6390-DSAZX8098-LLAZX8181-YHCMF1098-TDVUQ7277-OZCGZ1557-EMYVT2799-ARNLO2321-OMBXY5020-ZSTTY9880-TDQAC7102-JJVTX4983-CLMLV5701-YVSVF5804-LEPIM5697-GOMBF2739-CACDQ9385-EHGDO9498-FIMXL0122-OAHPZ2868-SNELZ6680-NENYN2088-IEBAU7982-VCELR6035-BXTTY6885-PKOAM7520-HQWJU5924-SNGKP0021-IKXGC2034-GDRCN8966-SNIZF6243-OZGFH4654-DLAMQ4115-NZRKS0623-IIHUG4572-DVCGN3351-NGXYI5229-DTFYB5176-LMJXE7302-ZHMHP2805-EDJPQ7156-MXBJE9601-BRXPO2863-IMQDR5651-CRHKQ0533-BNWKF1708-PBBOA3597-MVHJT0224-RLWWD9967-ATRFS3951-NJCVI2977-CEBSX6599-CEBNN5876-QMYLD2277-AXSDC9442-JTWDL3067-SVMTC4800-VHZKI4163-NCJAK5233-AOZUF1996-DBMUS7916-VCCPB5249-QYHEX0578-SKVMF5564-NEMQO2233-FAGXV5605-IYGFG8111-BKVDS2055-SIFSS8734-DKSTZ6152-ONASV9063-ZGTUY7781-HVGMK2320-SLKMB0771-WLCLA5628-RKIFK0206-TBWLC2937-FTHUR1910-FMXJM7752-XUSCI4110-PFEUZ0732-OCQOC8592-PLTMQ5760-WRAHC0256-LTHVJ4785-FCIFB8313-NDOIA0942-KOWSM6614-VBEGU8896-RAZCR4640-UHDOS4933-IKULF9399-APLBT4431-EDMIQ6227-HWPWX0447-BEMNG4612-SSVHJ5168-MQQCA5949-XIKAE9094-AZPHK6778-YSNIH0388-EOPEX0505-SPOOW6235-VDHOM7783-YKGDV4513-CXYIX3957-HHLMR7803-XOCCZ5609-CEBID4636-QRJKY1135-LMECX5956-VKDTT8677-HDZEE3482-ABPKK6705-LXORM0257-ZESQC6825-UYPFK0356-OBMAC8067-NIOYM9282-IZGQK0621-HJWXJ5844-QVTAT8905-IAZPF5394-MEITZ6859-QNXIQ2782-LFZVW2866-IKBTM2560-PPCHE1352-HNSAW1982-FEBTD5791-KAJFD2654-VBVPB0939-YAPAF0308-IVGOK7293-LSCDV5756-JYOJT6030-REHUX1218-VKFPE3627-FHKBK2865-TCHJW1423-BMPBQ2393-DIVAI5192-EBGOV0719-SYFRB1096-ADRUX2731-GJRDG3419-SNJJD4765-OXPPD6689-VRRTK9396-ZSFLL7134-MJPDY5240-CAOYT4059-IIEBK0516-UXRMT5148-HKFIR1009-IRMNA3003-CMDUU6797-UCJHZ2469-DTSGX9931-KGHOA9411-TPQQV7207-RMRDB2077-DDHJK4580-TMHJU4908-XAXAY8404-VLQFB5644-PDMZC9576-ANLXO2024-BASKD1140-UKVZG4160-AMJTL5650-VDUDS8095-WANWK8755-OGKNA2800-VEQXM7538-GWHML3859-CVCET0214-JHPFW5642-MHDQT3276-HDUEG2324-AALNO0822-GAVAP7501-IWUNG7251-LJBQN8040-MNRTF1536-HBSWP2276-YDAVZ2682-KEVRP2480-JZOSN6942-LBFDP7133-VBDCG7596-ZYWBB7929-DMBCV9661-JALZV5433-KYGHE0114-IGABW1853-ARAAQ4952-YSOGZ4950-HKQTE6786-OBWQR2684-EIWEO6439-GTPCA7564-GHCVB1173-NOEYG6647-ZEDXT7503-MIOGA4381-MHQDC6923-JHPMP4018-PPNDW1635-FJFCC2499-AJYUA3966-HRMZA8405-IGQFX8224-IVVPA0139-IVFJG0030-FNXPP2189-WWOEW5684-FJVYR1894-IGFSG1266-NZYUI4718-DHSMV3900-AQPHZ5842-POCOP8823-RLPWL9505-SQFSW3758-CKOQL7521-AFHAB4678-DVQEO0691-IFBQW2202-OUTMO0810-BDHAW7131-ZQZNK5726-CVNYA9871-ELEYA4257-GAESD6286-ZHAOK3807-XHCJH5671-RQRLP1450-GALXR3174-AKMAS9926-PJHDQ8098-TDCBU3196-NVXLZ6275-YDUVO0036-IHMOT4220-TINQT4335-BSMJS2311-QYMUQ9146-JRIOX9101-BWFSS3487-EARAT2672-TGEFF9231-ZJYAM0727-BMPLR0392-BZIUW1038-ZAGBI6549-NNDYT0422-OHQHQ6916-HIJSE2316-ESMLS7408-OFWXJ6007-TCTST7905-TVXTA7695-PKLCZ2382-BCKQJ3224-DFQNQ9944-HKVVB2732-ISEZX1937-OTUKY5073-WXOYN3050-GBUSH0207-MDKNV7876-AEHIG7945-HLKEA3908-BLSYF3199-NPKCN5170-PTRKA2123-AGEEN1258-YMZNM7549-MYGPK9227-LUNBG7997-EASSD0678-RLHVP4315-MURBD1051-GEJLJ9734-YWGEX5285-MVEHD4694-PHWFW0835-JKADZ7508-SMHXL3956-CJUST6103-BOCOU5149-TGWDZ9199-PWQVC4824-GUCBY5393-HJZSM7074-IEVOJ9625-QSTYE0862-PRCBS8812-ZRHFP5146-CBVOE4750-ZRXIU4198-VFOEA6630-UJZMY6400-BWQKW2692-AQCPF0347-UBKUZ0835-DUUIQ0811-GSDTP6115-ZTBFQ6353-BRMMA6680-WKXRZ9904-EHEVJ8584-KMVXD0851-DFJKB3261-CQXOL5651-YLPRD4849-PYRLQ3429-IFLEM3158-MOERK7294-TMAOP0604-THJFP5879-SESNB6461-PPAXN3318-ISQFQ2483-XSSMZ8165-ZJRNM9369-XFEHK2604-XVDAM1206-EHBDD8361-LBRDI4883-KCPZJ9108-EQPNQ3842-IYKUE6641-XRPSU1374-DMZUI8357-EQXFO8917-FAEMR2858-EIMXH9524-EGPJC6993-OHLXR6614-YOLAC4065-JJAVA9361-YNQWJ9391-TTOYH1452-XRSJV8242-SOQUO7460-ITWWP7868-TMWMZ6732-FZUGP4184-TJFAN8329-GWVPJ4145-UQXUQ2632-TACXW8146-QQKZH4581-LNWUM1915-OAKWD7296-PIXQY3354-OADJP3524-WQDSG0810-DHDBD8329-IBCTI3845-JHAMY7013-PSXHK5669-SRAIP3486-NPGST6941-PMGEP1624-WOIWJ4829-ZLJTK1730-VFMWO3800-LYTRK0634-SZPQA6166-ILMNY3097-NNSPB4194-WHFCB4121-AGSIN4361-BKAXE9845-PEEKO0455-XFASS9170-ARBTB4441-NIHPT8999-BOHSE4546-FOKWR9036-CSKBW8659-IOOPU4646-QZXTF4712-UYOOI7363-QTBIW4159-NAAIX0971-QIFJK9397-TZSHA9763-PDTKK2176-LVPNX7627-JKIAZ8461-EFQYM6891-JPYFF3696-XRIEN4081-DYXAV9330-DHBFL8257-RZAHR5293-WXJAK2208-NQBCT1779-PWPMG6621-NRZAK9553-DLCLU3522-CDKHF0411-EZJZE7851-WZEKY8807-ARQET8992-CEUEN8777-PVYGU8292-ITGYJ0621-CXBKL5268-DSMNQ5334-JLAXU4086-YQSNZ6242-MBHPK9359-UGBTK0135-NMXAP4782-OSFXZ7129-ACFOG1641-RQDAY6994-ORCWG1346-UFHAX3992-YWPKO2933-XEUJM0887-WBJVH5673-FSSMF7670-ZBPOQ8089-UZWLX0080-OROZO5232-NXPAY8967-SZQAS4468-KAZHE5542-NKVRU7126-RBHSD6789-HJBWG9087-EYCPR6077-BDPXA0013-MHZWF5494-HECPR1373-ORVIZ6980-IMXXE9897-KXHCM2294-DMMUS1618-CFHME6581-NQCBA7115-IRDHS2040-VZIKE1299-AURJA5565-FILXA0319-QZTCO0668-OGMHD2223-KAGMX9408-HRXRK5593-SUAOO7321-PKUYW6766-HFKLA7595-EUIVN2026-TGDHM9220-ZNKJI4030-VPZBD2226-ICFDO0723-VSOBE5529-GIBVH4187-CINZD4741-WWJQZ6625-UTXEW6818-WOBHJ1251-STYSZ4598-ZADCK7182-OVLBJ5095-ETBRJ7005-CYUIL4821-WQOYN2388-LAESQ9531-NSBMR4389-UEFCZ8985-OOPOS8800-ZKRFW8390-FESFV6248-TKCQV6729-GDNGC6198-ZFIOJ5989-OMNJE4566-QVRRW9795-SHUHB3230-IUALN0042-RLHYP4945-RVMTE0201-OAMXR1866-NXPSP7831-QGOXH6393-WRYZE9831-BPFRI5158-RIVOP9277-JOOMO0114-RSRRW4565-NLZBV0031-PVLZI7206-GZCDC6682-VCIXC6475-VHUIZ3910-MRQOY7537-RBWEA1768-ZAIFU3733-LSYCE2017-CCBLH0536-BGFMZ2293-IJWPS2845-HSJCY2625-TRCZQ4102-HLENU9415-DPEWS5624-RYAMH0196-JTUQI7943-RQCHR3793-MMFUH3084-DOWLE1084-MNSMJ5478-JJVZK7596-IIWYC6567-HOOPW1839-FBNFR1697-BCSHV0562-KBDVM4538-WNTMJ3334-CTHOL4704-ERYFC9432-RUVSL9089-UOWJG8621-MNIHH8039-ACLPL2592-YKDIF2272-JKMSI9518-RWHZL8714-CTZJW3569-EDBPQ3131-NWVFJ5419-CONWX6240-EURKS1970-KKFWL6960-HVYXR5678-VFNEQ5977-CKHON7024-OHCCK7861-UVUFT4859-ZSRDZ5651-WYIPH8785-CJSHH3870-SPZSI7560-QRBXH6510-UPNKS6718-BDGHG9052-VKDUW9546-CQJSU5777-KJIRB0506-LVNGN2480-EJWYP3253-HKOKL6806-YDEUL1621-YNCJH3473-XIIIT3070-BDOQC4763-PGDPO8970-ANWXO6979-TNDEU7079-QRCBC6048-UWKAL6281-FKEWS9290-SHCMB0743-HNPFG2277-BKJKN5208-HFSBT5035-PGZXH6543-JXSOO8016-ZMGMO8605-ITULD2667-WYLWJ4472-VESGY3128-YOVTD7041-TXQJH0481-SUMCB1769-GRUIK2811-POVEX9972-EWRJS9314-IJWSQ0661-XEYAN5799-JRCZO1921-KYSAY6198-RTPMF1925-GMVBW7881-EVUAD6184-DYUOB5766-XQXMQ1656-DRSMG3012-VFFMN2984-AFWNC8096-LOIST9764-REAFF7107-UBYKY8519-QJGJD7876-DNYAP2091-GPPIQ5071-FBJFS9798-OPFEM0330-IVZHA7114-AEOZE2886-KEFUM2245-ADZFJ7776-QGYJC9651-GTSAQ3186-BAXNB0637-YLETY9818-XQCUV8259-NFJTV6968-GMKPR1436-ZMJAN0799-DDIHE3070-FNFZQ7675-OZCZG5312-TSZVC0993-OSGPT9254-RBFON1205-WNWPJ7108-DGVUU5127-BZENZ2720-FVBQP9906-NHHVC3766-EJLFL8152-UOBNY7351-KYHQH7643-RCHXS8387-MOJJT6485-QXWWE7321-VGNKU5816-JMLGY7459-RRWQZ1971-DTCZB2812-REYAT8017-LXHFA6022-KOUQO6352-TWCAU2361-UPSND6035-RIIOM2929-QNSRW1262-OPMFY6267-DCFFZ4248-QPAVC1478-VPOAD2988-PLAHS1371-OJCEK8883-ANODQ2351-RRBUE1498-DQNRX3331-HQDTW9490-DFPMD2581-VKIRT2851-MMUTZ3049-NDXFL7963-GQRMY8189-HBVRW3761-FLYZI4829-AUOAX1219-NNDDO8388-DMKAE9659-QEQSY5405-ZMYXQ9158-VCTQB2808-CHTDM6311-UEUME0793-TWELN1060-ENTOF4836-WNFNO4422-QVIJA6839-ITVZJ4735-BJKOU0375-HVGXO3795-GWTRD6223-DHJGV6097-EQISJ4423-YLHDV4918-FYJNT4854-CIDCF6435-SRWBJ9964-WBQDJ6303-KFWSL0386-CWRGM7279-NMVJC6407-UTSLV4116-TZAQJ9060-HJJRW2587-YNLES7398-SKNQZ5935-FCCNB8345-MVDYC8375-DKEBR7551-JOHTI8887-IPQNC8646-JCOMS5318-IXUZF8952-WCVCD2418-TPEUN3963-RYFNS3198-VELRD8540-ZQGEA4137-JOPHL2057-BOYKM1803-BGNBD0134-XWXCE5848-FHRFC6519-CFDBX0409-WTMPL8763-KIAFH3669-WHAFY3055-VTCGS7279-BUYWN2007-QVGAW2155-AMQRX5091-HFAZW0516-VRYBW8623-ULFNQ5687-DKDTV7530-HDYDS7789-HKSBS7416-CKTEP3096-IZETN2348-KCJLT5377-NDTOU5922-ABDVO2474-LCNUE0839-QNXME9172-ANCRX2773-MADBQ6016-LVTJQ6910-HADCM4816-LXZYW5149-QYTTU2070-XYMFH1927-QEWMY6701-DHKWQ7554-AKDQF4911-BANWH5423-BHIXO2959-EEXWB3402-XRIUO8356-WUAOJ9350-ZXYJC8958-JPTRR3173-WSSUE1098-KFQEC7190-XHTWJ3537-RYBHH2485-ITVKB1612-EOHDH4510-PYUSH9359-JANWS7517-SAWMO7054-LGEQW0523-VNGTF7105-MXJLL7940-UQQUG0923-PNFUB3062-ICYZQ9938-PRCVK0973-KYVNF5129-HHMZC8840-DQLGN4547-LYTDD9894-QMIMJ6770-XUAGN4193-ORFCL9281-PKKZE6689-TCZHQ5777-ZPQNC1022-RKXDR2272-UOINI6637-KYRCV5668-MEISB7188-CBBBA5356-CSVSQ4720-VSTSI3219-JQRSL1845-CSBRZ2123-VSCOT2484-DGXPZ7409-JURKQ4587-NUKOX7297-DVYGA2239-CGBUZ0854-UYHZD7243-LCGGZ8229-BUJHX5504-WSIUR8183-ONMXC0564-MUUQK0701-RFGFI0019-EFAEP5619-PTMIK5882-CMAZQ5846-QFDFI4445-KWOKW5447-WZAFP5110-CHOPY5445-UTODQ4425-OWHWB7892-QVYKW0602-DDUML2208-MPXIO0348-SDKOL4373-MAVJG8901-HJXTF7710-JSYOA5419-KLXBN9885-MFVSU4514-GFCFI3365-SAIGS9828-AOQLM8000-REIQB0266-CLZKZ7615-ESMYF7020-OZKXZ3977-QCRSL1447-PJGGA9139-WQQDY9430-FRQOC6845-RGTYS7328-OWMOM5155-AZQPB8861-HGGKB7065-YUNRY5989-PGKJB4795-KTRTH1488-PBLJN3778-FOAQW4452-ROHMO5349-AZPEW3753-TSEMP8100-HZZLJ8309-IEYJD9172-JITSM7361-YPXFS7519-JTWQH2538-OIMXF1170-SASML4872-JCVCA5346-BZCHP2038-LLMLM9734-UYXQI2189-UXTKY7996-MHXLW7061-OVMIM5153-RTHKF6356-ELRKD8624-GIOUT3392-EHMNK6179-GJPSO7228-PAQPD3177-LASXD5934-TSSAU4897-QSUYC8290-YWKHZ3806-DXQOM6784-XYJAE3933-DQPWX6661-EIPZC8957-THMOA1057-FOGLZ0761-AETCS2190-BCXEC2153-MREFK3106-ULWFW0925-VYDLG0842-IWYCP3744-ZBHON8383-SGHJU8984-HPEMB4139-DETXS9779-DPNEJ5793-YOLJN4123-FCVCB8311-UEUAB8051-HJRLT8974-OVACP4010-YLMVT6288-CHQJB8160-HOWOX3023-GFLBR4223-BKEOR8894-JVDCV2014-MKGMH0248-IPDFW7978-DKUQH4335-UPJSI0524-IAVZO2737-YNGYW9297-FVVDH8007-YYPWD7101-HRBLJ5159-YFPKQ5039-LZRQT2931-VUVJN6418-PIQSP8220-OCUFY3995-WFCSM1895-QTKDO1178-PZGAB7927-AUXBZ7311-MQJCH1136-XGEQU4695-WJZUE3689-MOZGR3988-RQIXO9891-NQDBD6131-IUNXN9798-DRYDS6296-DDOOR7951-VRDVK4285-GYRQC7216-EWTRS7036-TYDEC5802-ADBRC5197-YPYBZ8337-MSSXB4312-GVYNH8495-LJDFO0839-JTCUD5494-WOZRZ8619-IJNDK8182-BJDSI3298-QEICA3597-YASZG9917-KWRBE1393-IMKZG8069-RHUXK3398-GCPMU2908-WGAXL1013-QCWAM0866-QLSIR6050-FFXES7181-BQYBV0362-RAOQO5527-ACHSO0829-DDVLK1813-JLKWR9537-VHDTA4957-TIALW2054-PJOCK9030-QGZNL6204-IEUXJ3126-WQMGH4529-CKBCL2506-CLAKW9239-GZHZE7205-BAIAD0151-ONTOV4140-MUHUG0093-EXYQL9168-INPSZ0015-UOCOJ2754-SDJRD9578-VRMNM2135-DQWAQ4056-QHXHZ7470-MCQTK7488-MXJIV7401-JIXNM3870-MQAMG6177-PEVRA4800-CZMPC4813-HQMGZ7245-NIIWQ0002-ORFBO8552-OBVRU8197-BFWVU6770-UAYGJ6463-HHXJR9776-OJUZI1306-RPWXZ8949-JTMAY2774-LVQUS3097-PYWXL2266-SJNAT0869-PAPRP4238-JSSWH2972-YDYUW2809-ILCYT5499-ECUTN4981-FLTMF4612-THJBS4094-NSEDU0234-TEVTT4304-TSPVK1552-AAGRX2637-FKFSY9796-MVYXX7874-ECPQJ0020-INWCK8739-XNIKG9755-JHNMN9251-WNSOD6974-DAFLI5103-MHMHY1846-XWOQN0235-KGSLC6650-BWFRT2712-SYWAY5498-IBWPI0013-SMEOE2884-GBPFB6114-TCFID5156-UMKOW1247-QBVSH9822-OAOVB1226-JZNKR5136-KCKGI6486-LHTMA4083-BFNYK7389-KBFIT7176-WIONM5141-ZUVBH0310-SUCIN5197-PYEPU2929-ERCFZ7548-SEPYI8835-VSDSE6619-RPLQZ3503-TYDAY1623-NLDOT9621-OUPYD9898-KZQDZ0141-YEAYS2450-ZKEED1133-KXCGE5236-PERKL1049-FYSYG0023-UYUPN1465-WCZVT9481-SFCQY6360-SVNWV0567-GGCAC7089-IVVAZ9050-IKDZA9802-CAQUT1254-IZEYF0187-WZNAB9492-TOKRI9221-OTIVJ7602-MVRMB1197-BVMVG5406-KGRMX8481-YYXWG2230-XTUWL7706-YLMQA2609-IAICY4716-MRVEN2143-LJULT1323-OOEPC6164-HXUGH5630-IXDXV0320-DWVTU9588-OZDMQ9921-ZVRHG1174-FGIFN1032-MAELW1552-TKMXS8622-ZLFKO6188-UXBBR5702-SKUOB9067-YGSCA1776-SPBWV8735-SDUFN9405-GPBBG1926-QUZNN5829-NVSQN8922-LIEGH8869-LIHMK8245-UMPYT5788-YPOEG9081-WWXKP8931-GJJIQ4277-PVRAN0722-SVSFK3612-YVGSJ9825-YCXWZ2000-DHJUY2050-ONYDQ7055-JCGNI0739-UUAJR7285-KLOTR0654-PQKDW7175-NTIXE7963-SHNDT8129-GMVGI2882-DDZPG3547-LQRIK5843-TTHGI1849-RJYIG5380-XPJNZ3230-JCNZS7996-BPXHY3227-WLKLI8237-ULIXL8216-AZUUZ9153-BTBVV4074-SJFFA5186-PEIZU1074-AMIOH4910-GMJOT0354-WYROK7748-UMTRK7145-FEJWU6463-MVYRY3969-JQABI9624-EGDEQ1051-EQPZR5780-INQIK4526-ZJJTM8384-FZBJK3750-RNQKR0962-CQPWQ3096-YXENJ1265-BCFEO5837-LXSDN8325-QRPZR6384-VMJHP2262-SLNVK7730-CLDSV1135-HIORI0164-APGRB6481-ESCNL1790-NESIO1550-EENBN5202-IVJNU8198-RKSZG0137-OCGAB3351-NQLDI9297-EONCV4588-YBNIB3336-JORSO3130-ICDUP4611-ANLQC4213-HKBJO2792-LSHWX9018-PCIOK4837-QUSFT0907-HQNTS7665-NKLAV8250-ZNGGW2195-ZRVAX3550-SAHFP8562-GHPPI4986-MXSFP3027-YNWZU5609-IMCGG9481-WHGWY9565-DJPIB4328-VUFWD3301-LSLWQ7473-ZBDSN3166-PNEOF8780-YRMTT5140-FOMCQ8454-AATJP4659-NZRUF4531-AUZNK1855-CFULU1872-EBWSC2608-BHKFN8128-YVJRG5781-BKHOP8628-MFKAX7629-WIXZF5445-GLVOT5472-CVMDX6461-SZMCV9508-ILZDG2346-DJQTB1697-LYYYX4749-VFKVB9640-ZSLDC4231-LZUYM8510-AWCXC3594-BDSOA0431-APWVY6838-YAUVY7883-ROJOC0244-LGNFY4295-YURET4236-UJPWO6402-SSEJG1143-NMNQJ1110-KYLGQ9929-PLVPA3518-PZXZQ0924-BJCRC2351-BKRZW4455-BFSPD0415-MOSGF0815-MFZGM5480-XTFFL7909-FIOIY6857-VWJDT5624-BQSSA0197-PNKNK2408-WITXK1229-RCALF3572-UOLYZ1429-UYJSV5577-OTWWW6366-XIVKZ3470-OBUET6599-GZWCM4404-HIBDJ4760-THGOT7295-JOMMD4016-BJKTZ0581-MDMPW5013-SBUIH9163-GHAYE5353-WILCI0709-TVGUR0058-EVZWM0519-DRGTI1017-FBQMM1985-MBRYP9372-TXXPS8433-WPJTV5804-JMYIO7599-NTMDP0536-ACXIP0936-NQLJU1575-KRZZE9170-GYZJC3638-DIMPH2454-RPBRZ5993-JSUWV5387-ASZNZ2002-MZHWP3097-FQTVJ5465-BUBFA7299-GNVPL1215-VFYVK9371-BITHB2265-CYWIV9093-FPDLG0541-FITGH6985-HAYWX6838-HVLXG1897-OKVMW0233-FTHAV7771-CFQRQ9512-PHSMG2004-OCQXK3617-XLSGQ7517-LDMPS7244-KXYZN2672-HUYVI8148-NLEGT8347-GDTMP0310-MVLET4003-OCTMP6652-YFFJO5248-RPYWW3170-GWYKC7409-KIUTL1732-VHUBQ0495-RVCBF8869-TORSS7446-SFAOA6505-OZNPG0679-IDSTG7765-LWVVH1658-TJVOA4692-NNQRU7742-MYPGI9619-GSATL5622-UEJFI9747-DDZOS0301-FIDRB9453-PATOS3348-CFRNX2931-XIQBR0106-UGRDO8059-UDZFY0208-BPQEJ5312-IRCFR3404-JNXAX3489-VSFRD5260-UMPWX2249-YPRNG7410-YTJIK2674-MIAHT2576-HXMPA3237-AJGEH4707-YNOQA8648-PFRMP1163-VIPRI9348-ROUAI0596-BQCEQ5598-IKHQQ6765-MBQNU9786-IJYDL1303-SRDOK3769-MHZNV2207-QPJED2209-XADXF6620-JDYNW0516-QREYC6022-UGGSO8084-OIVBS3352-RICWQ2065-MMKGR4484-CGXFK1402-PTHGN6214-EDAKZ1796-JANOW6127-ISGTU1614-JBEBI3923-CSIHK5795-KTGUD7924-GJZFI5897-ZYEKH3677-IYRBF5692-FPTAH9114-AAFQH8715-KKTFG1550-LOAHA1728-BQDMA0268-QKIWO0876-WDUUZ5117-ZSMHQ6465-GSRCL2858-MOFSQ7503-EPSZW1666-JXLKU7855-DIWPO5652-MSDEY1784-BXEFA7351-MHQVU9500-IWPXQ5762-TJXGK4504-YOULA4250-FDVOU5277-ZLOOR2141-RRYGO6979-ZNSFF5680-LQOGP8189-DUKMV6032-IGALN1898-JSNDC3911-RSNHI5505-OVWQW7271-AJDTL1867-TJHTS0516-WJVXC9174-FKWZE2817-LVCPP5038-ETMLM5056-FIMPT6569-KTMDU4822-NGOCH9391-DXGGG9844-FELAJ5307-DZCVC3148-AOIQT8679-JOEVF9754-CLVZW1432-FPAXX8336-TAVKX7168-HDQHG4803-AXVYP3884-HCSWG4567-AKPIA5077-DXTCG2919-HBCJO4236-XPXAV8903-WMRNW2452-SNHFZ3629-WEAAM9909-DFRJA9099-FTUHS0581-BXBUB9467-ROOLM2253-KPMNB5148-ORICT4893-GYUJU8908-SLFCJ9766-HGEDE5044-XDPYX3721-WKIIL6734-CKRSM1265-ZFOSD6568-POCUI5197-LQXXH9907-SWKKF3457-PQBYH0587-DMGBH5384-ZTTWP1407-DIGZV6397-JNZZG0570-BFQHT4393-OBCRR3523-QRQLL3696-DFHHB4717-GHADL5879-HMFFH3810-DVDQQ6972-SNKKW3694-GLTJM8149-RSOUN9055-MOJJJ4359-INNWN4032-RMHCI7250-EQKIY3594-IVHJZ3896-ZVNET4013-UBXWQ4931-TRZWN5519-NPHVG9938-EKRGF8173-RXAYP4825-XJGDM7850-THJMU8849-GYOKR3665-JATSN0461-CVKMU8853-TZDGH4324-BZCKL9710-ZUSHQ8123-QBNAZ4827-LTQRJ9620-ENEJV2378-YIZKA5498-TXHLF0689-DSXGL6818-DJXAA0464-WJTKO4132-KALRO2874-YXVVA1245-HARPS4210-QFJMF4293-ETKAP1085-LDWAM1843-TLSGD9626-VFRGG7075-BNDVQ9143-CANJF7284-BUYEC2041-JIJCI1086-LXKFY4900-MSOMT2229-VWQJH9194-GFVOI1336-EZFZY1403-LKLIK2636-ALXXZ7786-WBJYI9643-AVVWI0253-ZTEOB2706-QZIHY6061-PQHMK9885-CSMWE6137-MFAJN2402-TAIRZ9139-TWBAS3866-MDTUB3913-RDSJZ8058-JMEQO4203-QGNZA5043-TRZWM1640-PLFMP5366-OBVMR0337-CNPZE8380-MQINP0840-DFEZH1513-XNPPH8690-ZVLCL6015-VVHHE1125-SNVCK4616-EWBNJ1335-HQMKX2545-EBUPK2172-EJXVF0897-FEGMU1120-BMWUB9124-LHCJQ7029-IJEJK8871-JLMHM2235-ZGKPT3891-PUQOD8659-HDIYE3658-KIBGF5519-YLDGW1370-GGAWX4680-KUTAJ5307-UVGNB4946-EDSEW2516-VQRRV7580-UGXNC3642-BYHDO9629-NHXFW0396-HUJBP8879-ZKJOF4585-HETAI1474-JUWSM3530-CRZSB8498-XXGWA7636-PEPNS5578-NKCXI1642-HMARX3096-WPXBT8434-PNQZX4299-OPXEJ4951-UKAAQ9618-LFJRU6693-DJWTY0744-GKNGE6447-EGDIV1167-OYZJF2108-YKQTY4806-DXQCE5294-DMSFH4837-PZTIC1625-JAIIY3272-VUHPV8663-UPDGF6719-FGEDO1837-YQUCE0369-ZGOVK9919-KNPOO7872-BAAZR8174-TBVCF1877-HKBQX2746-DIJLO3508-VLHCZ4086-ATNFV7047-FWEYA2000-MPKCA5473-KHBPS0326-VDYXE6773-LQTVT0436-TWFFZ8566-YPRGL0311-UNPFF6609-MXJHJ2669-OIDSD8400-WZICQ0410-IPFTY9402-ORRAH1293-HHSHJ4840-ORQXB8610-ZIKJJ7801-KICAO7673-LPRNY8229-TNIQA7339-POGZN4465-VDKIQ2921-XWDJH9257-AZMTZ0975-UYDTX0975-VOOVL5569-KGJHX9799-CAYJJ0426-TIRNE5443-SCMKX8295-KMENE2368-GAKKQ3199-XGZCY6036-TTFYU2550-AEVRU0378-CJKPV4706-AXVKM5889-JTMUL1703-MGIAB4311-QTTAI9474-PHLYD4318-RAJVY2165-VOEGB2254-DLXRI1053-MXTTK1530-ZTDOZ6212-ATMLK7594-RQHXR1077-HUUJM2045-BMBTJ9677-AVKED1670-SVOWZ2227-JRSJX8980-WQFWL1730-ZMAME6506-EYCNH4634-JLRJT2560-QTSBS4795-WRNVT0260-ZDLGK6357-JJPQT9447-YPTBX0133-BMFZO6128-CZOMY9026-LHEVG2260-USTRB3656-TKRVZ7925-PNRGI1552-CZCLL3038-PQIUY2623-DRYAM9987-LUTYD4488-KQFDT2612-RANWT8707-RMEZH3346-BRMIS6479-VDGRK2933-FILNV3569-JFODW9544-PYPSJ1591-XWLGB3243-ZHOHY9986-BONCE2722-JMONI2203-GHNWN3878-AVSOQ5296-PSYVW6319-QSUSR7579-OOPEC0512-FLFDW0487-CRLZF2107-FBPTK9451-WLYRI1991-VOPLL9419-IPPBE2900-PHPLN0612-RTZZA8751-EDEKA6878-GGDWG8450-LUGUK3604-WLABM1142-IHLOO6410-LEFEN4633-MKHYU3194-ORPIK7826-VVKWT5442-BXVND8816-VXNZD9378-FXTIZ7825-GKXMW9753-OYLBX6656-JWRQX5899-MQZZL5312-UXESG9488-HGMJH6038-GCYEC2150-WLKUW7159-FVYPK7032-LMBHI1150-WFARN6088-BXMRG3144-AUDBS4821-SJHJV7346-MEDWM1137-DGOWI3812-LRZIR4818-QIUFN4227-OJHAL9220-CXRSC4877-TSOFF6688-UZPWD8468-EHYJA1097-FSPVW2839-RFSQE7010-ZMVBF0968-GSIKN9057-SIHCH6771-XWBDM3082-YVEKW0191-EQUUH7134-HBPBS3489-HHPFY2926-JEJJC8601-QACRS0508-OOLTO9822-WMWVG4806-HIPDW1548-ARAGG4415-WNGVR4615-PIVVU8885-QSQBX9385-NXKDA6674-KVJHG1814-DKOLC4201-JMNGR3537-HPKQT2129-ALKBS5821-MMEIL8260-NGFNY4742-TXUEX8800-JOOCF1469-LBJQJ2386-OWURY6712-OAWRH6278-FEPBZ8614-VGMMV2930-UOTMB7973-DZRKH5914-DVBWJ0650-BWOZN7785-RDVIG9306-CPCBC9504-YAZWB8819-ZBYNA1833-VGRUM6137-NICCO3620-EHIMZ6870-ECSHE8747-UDCOI4626-OZDTJ2325-ZUSFD8194-PEEBY6872-HXFNF3932-CMDTD7714-YXSMB8387-UGUSU1194-HVAIF3594-UVONA1767-TGTKO8805-JNRAZ5089-IFSDP0206-OYVOC0237-YFUTL1732-FEKLD0479-HMSWA4817-VYYWS5701-SVCWR3129-AAQOU4922-CVPDX1396-QWFBJ1099-BTKWT7340-KEFQE4570-QHXHL2898-LSJGD8104-OSKWT4521-YEEHE4090-KPJIP3786-WOVKF6086-ESGRL3886-CERTZ3824-RHKVR5816-SCGFC5989-AXPUC8590-OHDIW8015-IHCGW2332-TODQS9278-VZKCD8008-OTEZX5999-LCXAO5759-RCVCB6372-RFVNS8261-GWDBQ8938-UMKPI3882-IYOIJ3115-JPJDD9025-AOMKI7964-YESJC7716-YTYHG9938-ZREHM4647-MUZON8849-PRIQJ8851-RAGOV1304-NECVQ1729-VLAZJ8285-ABVLB5712-VBOXD6629-LADHQ8945-GRKHX4537-CIBHB3815-SLMEF5154-VEKBL4324-AHJKS4355-CVPVS4495-LHSSK9861-PDSZP4505-EXZHB4587-VVTOX7404-JLKQG7421-ZLUPA8972-HJWNV3274-NSDWE2632-IVXVF3692-JHONH5914-GXMDA7463-IFMQU8515-OCTJS3441-CGZJH2860-RANUS5261-QSHQM1200-TUZHR5884-FBCTL7625-XCQRH7634-WSWDB1731-TVIUK2987-BJXIK9769-TSBZE0406-BPDVR6023-GSSXW5276-KQWHG0420-HLGXF0582-AVCLN0743-HRVFF3727-JEZTU8143-ETQTI6689-KXGBO9667-TKTVZ3657-COGMW8570-KLJYJ7754-IXRMC9473-CBZOP2969-WGHQO4255-DDUOU5863-OOKCL1329-VHWNP5590-YRFJT0019-GFNTW4256-ZWTZI8309-PPCED4054-CUMIA0603-TPMIB2525-GVKQU2126-GSEGL3677-TNKIO0440-QEXBZ2434-EEVDB6762-QVYJO6199-IWKGC8152-VETUR9667-EQRXU9522-BNTHX3329-WDIOK7980-MHFLQ2873-ZLIWT3415-TAILE1629-DQQVB1915-IOFGU3045-XETSH0374-AACSZ9140-CZQZZ3

In [24]:
df.groupby('gender').mean(numeric_only=True) ## penggunaan parameter numeric_only => agar yg dilakukan fungsi agregasi Hanya kolom numerik

        SeniorCitizen     tenure  MonthlyCharges  TotalCharges
gender
Female       0.163078  32.290841       65.216652   2283.190985
Male         0.161736  32.550296       64.387546   2283.407861

In [27]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [29]:
df.pivot_table(index='gender', values=['SeniorCitizen','tenure','MonthlyCharges', 'TotalCharges'], aggfunc='median')
### menggunakan fungsi Default ==> Fungsi default dari Pivot_table => Mean

        MonthlyCharges  SeniorCitizen  TotalCharges  tenure
gender
Female           70.65              0       1387.35      29
Male             70.10              0       1404.65      29

In [32]:
df[['MonthlyCharges', 'gender']].groupby('gender').mean()

        MonthlyCharges
gender
Female       65.216652
Male         64.387546

In [34]:
df[['MonthlyCharges', 'gender']].groupby('Contract').mean()
### Ketika melakukan Subsetting dan groupby
## Kolom yg digunakan untuk grouping harus termasuk dalam subset

KeyError: 'Contract'

In [36]:
df[['gender', 'tenure']].groupby('gender').median()

        tenure
gender
Female    29.0
Male      29.0

In [37]:
df[['Contract', 'tenure']].groupby('Contract').mean()

                   tenure
Contract
Month-to-month  18.036645
One year        42.073370
Two year        57.071810

In [41]:
df[['Contract', 'MonthlyCharges']].groupby('Contract').mean().round(2).sort_values('MonthlyCharges', ascending=False)

                MonthlyCharges
Contract
Month-to-month           66.40
One year                 65.08
Two year                 60.87

In [42]:
df[['Contract', 'MonthlyCharges']].groupby('Contract').mean().round(2).sort_values('Contract', ascending=False)

                MonthlyCharges
Contract
Two year                 60.87
One year                 65.08
Month-to-month           66.40

In [43]:
df[['Contract', 'MonthlyCharges']].groupby('Contract').mean().round(2).sort_values('Contract', ascending=False).head(2)

          MonthlyCharges
Contract
Two year           60.87
One year           65.08

In [44]:
df[['Contract', 'gender', 'tenure']].groupby(['Contract', 'gender']).mean()

                          tenure
Contract       gender
Month-to-month Female  17.974026
               Male    18.098462
One year       Female  42.445682
               Male    41.718833
Two year       Female  56.420238
               Male    57.719527

In [45]:
df.pivot_table(index=['Contract', 'gender'], values='tenure')

                          tenure
Contract       gender
Month-to-month Female  17.974026
               Male    18.098462
One year       Female  42.445682
               Male    41.718833
Two year       Female  56.420238
               Male    57.719527

In [47]:
pd.crosstab(index=[df['Contract'], df['gender']], columns='tenure', values=df['tenure'], aggfunc='mean')

col_0                     tenure
Contract       gender
Month-to-month Female  17.974026
               Male    18.098462
One year       Female  42.445682
               Male    41.718833
Two year       Female  56.420238
               Male    57.719527

In [48]:
df[['Contract', 'gender', 'tenure']].groupby(['Contract', 'gender']).mean()

                          tenure
Contract       gender
Month-to-month Female  17.974026
               Male    18.098462
One year       Female  42.445682
               Male    41.718833
Two year       Female  56.420238
               Male    57.719527

In [49]:
df[['Contract', 'gender', 'tenure']].groupby(['Contract', 'gender'], as_index=False).mean()

         Contract  gender     tenure
0  Month-to-month  Female  17.974026
1  Month-to-month    Male  18.098462
2        One year  Female  42.445682
3        One year    Male  41.718833
4        Two year  Female  56.420238
5        Two year    Male  57.719527

In [50]:
df[['Contract', 'tenure']].groupby('Contract').agg(['count', 'mean'])

               tenure
                count       mean
Contract
Month-to-month   3875  18.036645
One year         1472  42.073370
Two year         1685  57.071810

In [52]:
df.pivot_table(index='Contract', values='tenure',aggfunc=('count', 'mean'))

                count       mean
Contract
Month-to-month   3875  18.036645
One year         1472  42.073370
Two year         1685  57.071810

In [53]:
df.pivot_table(index='Contract', values=['tenure', 'MonthlyCharges'],aggfunc=('count', 'mean'))

               MonthlyCharges            tenure
                        count       mean  count       mean
Contract
Month-to-month           3875  66.398490   3875  18.036645
One year                 1472  65.079416   1472  42.073370
Two year                 1685  60.872374   1685  57.071810

In [54]:
df[['Contract', 'tenure', 'MonthlyCharges']].groupby('Contract').agg(['count', 'mean'])

               tenure            MonthlyCharges
                count       mean          count       mean
Contract
Month-to-month   3875  18.036645           3875  66.398490
One year         1472  42.073370           1472  65.079416
Two year         1685  57.071810           1685  60.872374

In [65]:
df[['Contract', 'tenure', 'MonthlyCharges', 'gender']].groupby(['Contract', 'gender']).agg(['median', 'mean'])

                      tenure            MonthlyCharges
                      median       mean         median       mean
Contract       gender
Month-to-month Female   12.0  17.974026         73.800  66.652623
               Male     12.0  18.098462         72.525  66.147615
One year       Female   46.0  42.445682         70.125  66.841643
               Male     43.0  41.718833         65.625  63.401326
Two year       Female   64.0  56.420238         64.075  60.536905
               Male     65.0  57.719527         64.950  61.205858

In [56]:
df.pivot_table(index=['Contract', 'gender'], values=['tenure', 'MonthlyCharges'],aggfunc=('count', 'mean'))

                      MonthlyCharges            tenure
                               count       mean  count       mean
Contract       gender
Month-to-month Female           1925  66.652623   1925  17.974026
               Male             1950  66.147615   1950  18.098462
One year       Female            718  66.841643    718  42.445682
               Male              754  63.401326    754  41.718833
Two year       Female            840  60.536905    840  56.420238
               Male              845  61.205858    845  57.719527

In [59]:
df[['Contract', 'tenure', 'MonthlyCharges', 'gender']].groupby(['Contract', 
                                                                'gender']).agg({'tenure' : 'mean', 'MonthlyCharges' : 'median'})

                          tenure  MonthlyCharges
Contract       gender
Month-to-month Female  17.974026          73.800
               Male    18.098462          72.525
One year       Female  42.445682          70.125
               Male    41.718833          65.625
Two year       Female  56.420238          64.075
               Male    57.719527          64.950

In [60]:
df.pivot_table(index=['Contract', 'gender'], values=['tenure', 'MonthlyCharges'], aggfunc={'tenure' : 'mean', 
                                                                                          'MonthlyCharges' : 'median'})

                       MonthlyCharges     tenure
Contract       gender
Month-to-month Female          73.800  17.974026
               Male            72.525  18.098462
One year       Female          70.125  42.445682
               Male            65.625  41.718833
Two year       Female          64.075  56.420238
               Male            64.950  57.719527

In [61]:
df[['Contract', 'tenure', 'MonthlyCharges', 'gender']].groupby(['Contract', 
                                                                'gender']).agg({'tenure' : ('mean', 'count'), 'MonthlyCharges' : 'median'})

                          tenure       MonthlyCharges
                            mean count         median
Contract       gender
Month-to-month Female  17.974026  1925         73.800
               Male    18.098462  1950         72.525
One year       Female  42.445682   718         70.125
               Male    41.718833   754         65.625
Two year       Female  56.420238   840         64.075
               Male    57.719527   845         64.950

In [62]:
df.pivot_table(index=['Contract', 'gender'], values=['tenure', 'MonthlyCharges'], aggfunc={'tenure' : ('mean', 'count'), 
                                                                                          'MonthlyCharges' : 'median'})

                      MonthlyCharges tenure
                              median  count       mean
Contract       gender
Month-to-month Female         73.800   1925  17.974026
               Male           72.525   1950  18.098462
One year       Female         70.125    718  42.445682
               Male           65.625    754  41.718833
Two year       Female         64.075    840  56.420238
               Male           64.950    845  57.719527

In [63]:
df[['Contract', 'tenure', 'MonthlyCharges', 'gender', 'TotalCharges']].groupby(['Contract', 
                                                                'gender']).agg({'tenure' : ('mean', 'count'), 'MonthlyCharges' : 'median',
                                                                               'TotalCharges' : 'sum'})

                          tenure       MonthlyCharges TotalCharges
                            mean count         median          sum
Contract       gender
Month-to-month Female  17.974026  1925         73.800    2605975.8
               Male    18.098462  1950         72.525    2699885.7
One year       Female  42.445682   718         70.125    2248225.9
               Male    41.718833   754         65.625    2218827.6
Two year       Female  56.420238   840         64.075    3098152.5
               Male    57.719527   845         64.950    3185101.2

In [64]:
df.pivot_table(index=['Contract', 'gender'], values=['tenure', 'MonthlyCharges', 'TotalCharges'], aggfunc={'tenure' : ('mean', 'count'), 
                                                                                          'MonthlyCharges' : 'median',
                                                                                                          'TotalCharges' : 'sum'})

                      MonthlyCharges TotalCharges tenure
                              median          sum  count       mean
Contract       gender
Month-to-month Female         73.800    2605975.8   1925  17.974026
               Male           72.525    2699885.7   1950  18.098462
One year       Female         70.125    2248225.9    718  42.445682
               Male           65.625    2218827.6    754  41.718833
Two year       Female         64.075    3098152.5    840  56.420238
               Male           64.950    3185101.2    845  57.719527